import { StyleSheet } from 'react-native';
import { colors } from '../constants/COLORS';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.backgroundLight,
  },
  navBarContainer: {
    width: 250,
  },
  mainScrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 26,
    paddingVertical: 22,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  titleBlock: {
    flex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: '800',
    color: colors.primaryDark,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
  },
  updateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 14,
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  updateButtonText: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 8,
  },
mealCard: {
    backgroundColor: colors.white,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#dfe6ef',
    marginBottom: 18,
    alignSelf: 'center',
    maxWidth: '100%',
  },
  mealHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  mealHeaderText: {
    marginLeft: 10,
    fontSize: 20,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  tableWrapper: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#d8e0eb',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#f8f9fb',
  },
  fixedColumn: {
    backgroundColor: '#f8f9fb',
    borderRightWidth: 1,
    borderRightColor: '#d8e0eb',
    zIndex: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 0 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#eef3f8',
    borderBottomWidth: 1,
    borderBottomColor: '#d8e0eb',
  },
  labelHeaderCell: {
    width: 95, 
    height: 44,
  },
  dayHeaderCell: {
    width: 140,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRightWidth: 1,
    borderRightColor: '#d8e0eb',
  },
  dayHeaderText: {
    color: colors.primaryDark,
    textAlign: 'center',
    fontSize: 11,
    fontWeight: '700',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#d8e0eb',
  },
  labelCell: {
    width: 95, 
    height: 100,
    paddingHorizontal: 8,
    backgroundColor: '#f8f9fb',
    justifyContent: 'center',
  },
  labelText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.primaryDark,
  },
  mealCell: {
    width: 140, 
    height: 100,
    paddingHorizontal: 6,
    paddingVertical: 10,
    borderRightWidth: 1,
    borderRightColor: '#d8e0eb',
    position: 'relative',
    backgroundColor: '#ffffff',
  },
  cellContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mealText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.text,
    textAlign: 'center',
    lineHeight: 14,
    marginBottom: 8,
  },
  allergenRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  allergenBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 2,
  },
  leiteBadge: {
    backgroundColor: '#dfeaff',
  },
  ovoBadge: {
    backgroundColor: '#ffeaa3',
  },
  allergenText: {
    fontSize: 9,
    fontWeight: '800',
    color: colors.primaryDark,
  },
  favoriteButton: {
    position: 'absolute',
    right: 6,
    top: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginLeft: 4,
  },
  footerText: {
    marginLeft: 8,
    fontSize: 14,
    color: colors.textSecondary,
  },
  mobileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eef3f8',
  },
  brandWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoImage: {
    width: 35,
    height: 35,
    borderRadius: 8,
    marginRight: 4,
  },
  brandTextWrap: {
    justifyContent: 'center',
  },
  brandTitle: {
    fontSize: 16,
    fontFamily: 'Syne_700Bold',
    fontWeight: '700',
    color: colors.text,
  },
  brandSubtitle: {
    fontSize: 11,
    fontFamily: 'DMSans_300Light',
    color: colors.textMuted,
    marginTop: -4,
    fontWeight: '500',
  },
  mobileMenuOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 999,
    flexDirection: 'row',
  },
  overlayBackground: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
});